module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/JcaC26geQIQ9MMMlgICBuY',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://img.sanishtech.com/u/1b30738a5f508075d598208ec965da8f.jpg',
    NEWSLETTER_JID: '120363402507750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ʙʀᴏᴡᴀʏᴇꜱᴜ-ᴍɪɴɪ',
    OWNER_NAME: 'ʙʀᴏᴡᴀʏᴇꜱᴜ',
    OWNER_NUMBER: '254746432359',
    BOT_VERSION: '1.0.1',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʙʀᴏᴡᴀʏᴇꜱᴜ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6YML80VycDvHq6yV3S',
};
